# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import gpu_ipc_sidecar_pb2 as gpu__ipc__sidecar__pb2


class GpuIpcSidecarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishHandle = channel.unary_unary(
                '/openpi.native.gpuipc.GpuIpcSidecar/PublishHandle',
                request_serializer=gpu__ipc__sidecar__pb2.PublishHandleRequest.SerializeToString,
                response_deserializer=gpu__ipc__sidecar__pb2.PublishHandleResponse.FromString,
                )
        self.ResolveHandle = channel.unary_unary(
                '/openpi.native.gpuipc.GpuIpcSidecar/ResolveHandle',
                request_serializer=gpu__ipc__sidecar__pb2.ResolveHandleRequest.SerializeToString,
                response_deserializer=gpu__ipc__sidecar__pb2.ResolveHandleResponse.FromString,
                )
        self.Healthz = channel.unary_unary(
                '/openpi.native.gpuipc.GpuIpcSidecar/Healthz',
                request_serializer=gpu__ipc__sidecar__pb2.HealthzRequest.SerializeToString,
                response_deserializer=gpu__ipc__sidecar__pb2.HealthzResponse.FromString,
                )


class GpuIpcSidecarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishHandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveHandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpuIpcSidecarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishHandle,
                    request_deserializer=gpu__ipc__sidecar__pb2.PublishHandleRequest.FromString,
                    response_serializer=gpu__ipc__sidecar__pb2.PublishHandleResponse.SerializeToString,
            ),
            'ResolveHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveHandle,
                    request_deserializer=gpu__ipc__sidecar__pb2.ResolveHandleRequest.FromString,
                    response_serializer=gpu__ipc__sidecar__pb2.ResolveHandleResponse.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=gpu__ipc__sidecar__pb2.HealthzRequest.FromString,
                    response_serializer=gpu__ipc__sidecar__pb2.HealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openpi.native.gpuipc.GpuIpcSidecar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GpuIpcSidecar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openpi.native.gpuipc.GpuIpcSidecar/PublishHandle',
            gpu__ipc__sidecar__pb2.PublishHandleRequest.SerializeToString,
            gpu__ipc__sidecar__pb2.PublishHandleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResolveHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openpi.native.gpuipc.GpuIpcSidecar/ResolveHandle',
            gpu__ipc__sidecar__pb2.ResolveHandleRequest.SerializeToString,
            gpu__ipc__sidecar__pb2.ResolveHandleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openpi.native.gpuipc.GpuIpcSidecar/Healthz',
            gpu__ipc__sidecar__pb2.HealthzRequest.SerializeToString,
            gpu__ipc__sidecar__pb2.HealthzResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
