# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpu_ipc_sidecar.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gpu_ipc_sidecar.proto\x12\x14openpi.native.gpuipc\"e\n\x0cGpuIpcHandle\x12\x11\n\thandle_id\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65vice_index\x18\x04 \x01(\x05\x12\x0e\n\x06nbytes\x18\x05 \x01(\x04\"\x86\x01\n\x14PublishHandleRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tlayer_idx\x18\x02 \x01(\x05\x12\x13\n\x0btensor_name\x18\x03 \x01(\t\x12\x32\n\x06handle\x18\x04 \x01(\x0b\x32\".openpi.native.gpuipc.GpuIpcHandle\"4\n\x15PublishHandleResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"R\n\x14ResolveHandleRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tlayer_idx\x18\x02 \x01(\x05\x12\x13\n\x0btensor_name\x18\x03 \x01(\t\"k\n\x15ResolveHandleResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x32\n\x06handle\x18\x02 \x01(\x0b\x32\".openpi.native.gpuipc.GpuIpcHandle\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x10\n\x0eHealthzRequest\".\n\x0fHealthzResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbb\x02\n\rGpuIpcSidecar\x12h\n\rPublishHandle\x12*.openpi.native.gpuipc.PublishHandleRequest\x1a+.openpi.native.gpuipc.PublishHandleResponse\x12h\n\rResolveHandle\x12*.openpi.native.gpuipc.ResolveHandleRequest\x1a+.openpi.native.gpuipc.ResolveHandleResponse\x12V\n\x07Healthz\x12$.openpi.native.gpuipc.HealthzRequest\x1a%.openpi.native.gpuipc.HealthzResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpu_ipc_sidecar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GPUIPCHANDLE']._serialized_start=47
  _globals['_GPUIPCHANDLE']._serialized_end=148
  _globals['_PUBLISHHANDLEREQUEST']._serialized_start=151
  _globals['_PUBLISHHANDLEREQUEST']._serialized_end=285
  _globals['_PUBLISHHANDLERESPONSE']._serialized_start=287
  _globals['_PUBLISHHANDLERESPONSE']._serialized_end=339
  _globals['_RESOLVEHANDLEREQUEST']._serialized_start=341
  _globals['_RESOLVEHANDLEREQUEST']._serialized_end=423
  _globals['_RESOLVEHANDLERESPONSE']._serialized_start=425
  _globals['_RESOLVEHANDLERESPONSE']._serialized_end=532
  _globals['_HEALTHZREQUEST']._serialized_start=534
  _globals['_HEALTHZREQUEST']._serialized_end=550
  _globals['_HEALTHZRESPONSE']._serialized_start=552
  _globals['_HEALTHZRESPONSE']._serialized_end=598
  _globals['_GPUIPCSIDECAR']._serialized_start=601
  _globals['_GPUIPCSIDECAR']._serialized_end=916
# @@protoc_insertion_point(module_scope)
